services:
  - type: web
    name: pixtale-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 3000
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://pixtale-app.vercel.app
